
<div class = 'corpoCadastro'>
    <div class = 'boxCadastro'>
        <div class =' text-center text-muted'>
            <h1>Cadastro de Produto</h1>
        </div>

         <form method = 'post' action='/registrarProduto'>
                <div class="form-group">
                    <label for="exampleInputEmail1">Descricão do Produto</label>
                    <input type="text" class="form-control" id="descProduto" name = 'descProduto' placeholder="Nome Produto">
                 </div>
                 <div class="form-group">
                    <label for="exampleInputEmail1">Quantidade do Produto</label>
                    <input type="text" class="form-control" id="qtdProduto" name = 'qtdProduto' placeholder="Quantidade Produto">
                 </div>
                 <div class="form-group">
                    <label for="exampleInputEmail1">Valor do Produto</label>
                    <input type="text" class="form-control" id="valorProduto" name = 'valorProduto' placeholder="Valor Produto">
                 </div>

                 <div class = 'text-center'>
                 <button class = 'btn-primary'>Cadastrar</button> 
                 <a name="" id="" class="btn btn-danger" href="/listarProduto" role="button">Listar</a>             
                 </div>
           </form>
    </div>
</div>