<!-- <div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="/img/twitter_logo.png" />
        </div>

        <div class="row">
          <div class="col">
            <h2>Cadastro realizado com sucesso</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            <a href="/" class="btn btn-primary btn-block">Clique aqui para fazer login!</a>
          </div>
        </div>

      </div>
    </div>
  </div>
</div> -->




<div class="modal-container" id="modal">
    <div class="box-modal" id="box-modal"> 
        <div class="logo-user">
        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>

        </div>
        <div class="text-center text-muted tittle">
             <h1>Cadastro realizadoo com sucesso</h1>
        </div>    
            <div class="text-center">
            <a href="/login" class="btn btn-login">Clique aqui para fazer login!</a>
            </div>
    </div>
</div>
    
  