<?php  
    use MF\Controller\Action;
    use MF\Model\Container;
?>

<div class = 'corpoCadastro'>
    <div class = 'boxCadastro'>
        <div class = "text-center text-muted">
            <h1>Produtos em estoque</h1>
        </div>
            <table class="table">
        <thead>
            <tr class = "thead-dark">
            <th scope="col">id</th>
            <th scope="col">Descrição</th>
            <th scope="col">Quantidade em estoque</th>
            <th scope="col">Valor de Venda</th>
            </tr>
        </thead>
        <tbody>
            <tr>

            <?php
           

            $produto = Container::getModel('Produto');
                         
            // echo '<pre>';
            // print_r($produto);
            // echo '</pre>';
            
           echo '<pre>';
           print_r($produto->listarProduto()[3]['NOME']);
           echo '</pre>';
    

           for($i =0; $i < 5; $i++){
            echo "teste";
           }
            ?>

            <th scope="row">1</th>
            <td><?=print_r($produto->listarProduto()[3]['NOME']);?></td>
            <td>Otto</td>
            <td>@mdo</td>
            </tr>
            <tr>
            <th scope="row">2</th>
            <td>Jacob</td>
            <td>Thornton</td>
            <td>@fat</td>
            </tr>
            <tr>
            <th scope="row">3</th>
            <td>Larry</td>
            <td>the Bird</td>
            <td>@twitter</td>

            </tr>
        </tbody>
        </table>
    </div>
</div>