<div class="modal-container" id="modal">
    <div class="box-modal" id="box-modal"> 

        <div class="logo-user">
        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>

        </div>
        <div class="text-center text-muted tittle">
             <h1>Tela de cadastro</h1>
             <div class="imagem" id="imagem">
                 <img src="anssets/imagens/user.png" alt="">
            </div>    
        </div>    
        <form action="/registrar" method="post" class="formulario">
        <div class ="form-group col-12">
                <input class="form-control" type="text" name = "nome" placeholder = "Digite seu Nome">
            </div>
            <div class ="form-group col-12">
                <input class="form-control" type="text" name = "email" placeholder = "Digite seu E-mail">
            </div>
            <div class ="form-group col-12">
                <input class="form-control" type="password" name = "senha" placeholder = "Digite sua Senha">
            </div>
            <div class="text-center">
                <button class="btn btn-login">Salvar</button>
            </div>
        </form>
    </div>
</div>